Repository tads-cnat/fretex, pull requests merged in 2023-04, with the labels that each got.

#50 Refactor: forma de acesso aos metodos de validação no hook de cadastro de freteiro.
  frontend/src/hooks/useFreteiroForm.ts
Labels: refactor

#51 Refactor: forma de acesso aos metodos de validação no hook de cadastro de cliente.
  frontend/src/components/RegisterComponents/RegisterClienteForm/index.tsx
Labels: refactor

#59 Resolve: 58 corrigir erro de lint na página fretedetail relacionado ao valor de objeto
  frontend/src/pages/FreteDetail/index.tsx
Labels: refactor

#55 Bug/Refactor: Formulário de cadastro de pedido de frete.
  frontend/src/components/RegisterFreteComponents/Form/index.tsx
  frontend/src/interfaces/index.ts
Labels: bug, refactor

#61 refactor: ternários do CSS do componente de Navbar
  frontend/src/components/FreteDetailFreteiroComponents/ModalContraproposta/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/ModalProposta/intex.tsx
  frontend/src/components/Navbar/styles.tsx
  frontend/src/components/Profile/LabelInput/index.tsx
Labels: refactor

#53 refactor: feita a subtituição do operador '||' pelo '??'
  frontend/src/pages/Profile/EditProfile/index.tsx
Labels: refactor

#77 Resolve: 76 criar componente head para automatizar o título das páginas
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Head/index.tsx
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/pages/FreteDetail/index.tsx
  frontend/src/pages/FretesAvailable/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/Profile/index.tsx
  frontend/src/pages/RegisterFrete/index.tsx
  frontend/src/pages/ResgisterUser/index.tsx
Labels: implementation

#95 refactor: foi feito o encapsulamento dos dados do componente BtnTypeUser
  frontend/src/pages/ResgisterUser/constants.ts
  frontend/src/pages/ResgisterUser/index.tsx
Labels: refactor

#93 refactor: foi feito o encapsulamento dos dados do componente HomeBox
  frontend/package-lock.json
  frontend/src/pages/Home/contants.ts
  frontend/src/pages/Home/index.tsx
Labels: refactor

#91 74 componentizar inputs do frontend
  DocumentoDeArquitetura.md
  frontend/src/components/Input/index.tsx
  frontend/src/components/Input/styles.tsx
  frontend/src/components/RegisterComponents/RegisterClienteForm/index.tsx
  frontend/src/components/RegisterComponents/RegisterClienteForm/styles.tsx
  frontend/src/components/RegisterComponents/RegisterFreteiroForm/index.tsx
  frontend/src/hooks/useAddress.ts
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/ResgisterUser/schemas/index.ts
  package-lock.json
  package.json
Labels: refactor

#96 refactor: componentizar os butões da aplicação
  frontend/src/components/FreteDetailFreteiroComponents/FreteDetail/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/FreteDetail/styles.tsx
  frontend/src/components/FreteDetailFreteiroComponents/ModalContraproposta/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/ModalProposta/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/ModalProposta/styles.tsx
  frontend/src/components/FreteDetailFreteiroComponents/NegociationComponent/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/NegociationComponent/styles.tsx
  frontend/src/components/FretesAvailable/BoxFretes/index.tsx
  frontend/src/components/FretesAvailable/BoxFretes/styles.tsx
  frontend/src/components/Global/Button/index.tsx
  frontend/src/components/Global/Button/styles.tsx
  frontend/src/components/HomeComponents/HomeVideoSection/index.tsx
  frontend/src/components/HomeComponents/RegistrationSection/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Profile/Banner/index.tsx
  frontend/src/components/RegisterComponents/RegisterClienteForm/index.tsx
  frontend/src/components/RegisterComponents/RegisterClienteForm/styles.tsx
  frontend/src/components/RegisterComponents/RegisterFreteiroForm/index.tsx
  frontend/src/components/RegisterComponents/RegisterFreteiroForm/styles.tsx
  frontend/src/components/RegisterFreteComponents/Form/index.tsx
  frontend/src/components/RegisterFreteComponents/Form/styles.tsx
  frontend/src/interfaces/styledComponents.ts
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/pages/Dashboard/styles.tsx
  frontend/src/pages/FreteDetail/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/Profile/EditProfile/index.tsx
  frontend/src/pages/Profile/Vehicles/index.tsx
  frontend/src/pages/Profile/Vehicles/styles.tsx
Labels: refactor
