Repository tads-cnat/fretex, pull requests merged in 2023-06, with the labels that each got.

#125 Reatividade entre botões e estado de loading das respectivas paginas
  frontend/src/components/FreteDetailFreteiroComponents/FreteDetail/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/ModalContraproposta/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/ModalProposta/index.tsx
  frontend/src/components/FreteDetailFreteiroComponents/NegociationComponent/index.tsx
  frontend/src/components/Global/Button/index.tsx
  frontend/src/components/Global/Button/styles.tsx
  frontend/src/components/Global/Loading/index.tsx
  frontend/src/components/Profile/Banner/index.tsx
  frontend/src/components/RegisterComponents/RegisterClienteForm/index.tsx
  frontend/src/components/RegisterComponents/RegisterFreteiroForm/index.tsx
  frontend/src/components/RegisterFreteComponents/Form/index.tsx
  frontend/src/hooks/useFreteiroForm.ts
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/Profile/EditProfile/index.tsx
  frontend/src/pages/Profile/Vehicles/index.tsx
  frontend/src/pages/Profile/Vehicles/schema/index.tsx
  frontend/src/styles/globalStyles.tsx
Labels: bug

#144 137 teste de integração cadastro cliente
  backend/plataform/tests.py
Labels: implementation

#153 149 modificar o componente de botão para aceitar icones
  frontend/package.json
  frontend/src/components/BoxFretes/index.tsx
  frontend/src/components/BoxFretes/styles.tsx
  frontend/src/components/Footer/index.tsx
  frontend/src/components/Footer/styles.tsx
  frontend/src/components/LabelInput/styles.tsx
  frontend/src/components/Navbar/NavUser/index.tsx
  frontend/src/components/Navbar/NavUser/styles.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Navbar/styles.tsx
  frontend/src/components/NegotiationsComponents/CardsContainer/index.tsx
  frontend/src/components/NegotiationsComponents/ModalContraproposta/index.tsx
  frontend/src/components/NegotiationsComponents/ModalProposta/index.tsx
  frontend/src/components/NegotiationsComponents/ModalProposta/styles.tsx
  frontend/src/components/NegotiationsComponents/NegotiationComponent/index.tsx
  frontend/src/components/utils/Button/index.tsx
  frontend/src/components/utils/Input/styles.tsx
  frontend/src/components/utils/Preview/styles.tsx
  frontend/src/interfaces/IActive.ts
  frontend/src/pages/Dashboard/components/BoxDashboard/index.tsx
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/pages/FreteDetail/components/FreteDetailComponent/index.tsx
  frontend/src/pages/FreteDetail/components/FreteDetailComponent/styles.tsx
  frontend/src/pages/Home/components/RegistrationSection/index.tsx
  frontend/src/pages/Home/components/SectionVantagens/styles.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/Login/styles.tsx
  frontend/src/pages/Profile/EditProfile/index.tsx
  frontend/src/pages/Profile/Vehicles/index.tsx
  frontend/src/pages/Profile/components/Banner/index.tsx
  frontend/src/pages/RegisterFrete/components/Form/styles.tsx
  frontend/src/pages/ResgisterUser/components/RegisterClienteForm/index.tsx
  frontend/src/pages/ResgisterUser/components/RegisterClienteForm/inputs.tsx
  frontend/src/pages/ResgisterUser/components/RegisterClienteForm/styles.tsx
  frontend/src/pages/ResgisterUser/components/RegisterFreteiroForm/index.tsx
  frontend/src/pages/ResgisterUser/components/RegisterFreteiroForm/inputs.tsx
  frontend/src/pages/ResgisterUser/components/RegisterFreteiroForm/styles.tsx
  frontend/src/pages/ResgisterUser/index.tsx
  frontend/src/pages/ResgisterUser/style.tsx
  frontend/src/styles/globalStyles.tsx
  frontend/yarn.lock
Labels: refactor

#152 fix: consertar rotas de login e cadastro ao estar logado e consertar …
  frontend/src/components/NegotiationsComponents/ModalProposta/index.tsx
  frontend/src/pages/FreteDetail/components/FreteDetailComponent/index.tsx
  frontend/src/pages/FreteDetail/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/ResgisterUser/index.tsx
  frontend/src/utils/formatCEP.ts
  frontend/yarn.lock
Labels: bug
